version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:8000"
    environment:
      - DATA_PROVIDER=${DATA_PROVIDER}
      - OPENSKY_USERNAME=${OPENSKY_USERNAME}
      - OPENSKY_PASSWORD=${OPENSKY_PASSWORD}
    restart: unless-stopped
